### ISSUE TITLE
i cant create relations between projects and organizations

### ISSUE THREAD

**Issue by w0www** [jbbarth/redmine_organizations#4]
I add in each project the organization but when i reload the page dont show. The problem is that the plugin dont save the project in organization 

i try two method, 
first since administration > organizations but when i select a project, i redirect to project/settings
second since project/settings/members but when i add an organization and reload the page the organitazion leave. (Not save)

help!

**Comment by jbbarth** [comment]
Honestly this plugin is really bad and I'm not surprised it doesn't work in your cases. I think you should use Redmine native groups features if you can. Also I can have a look at your issue but for that I'd basically need what's asked in the core wiki (http://www.redmine.org/projects/redmine/wiki/Submissions#Submitting-a-Bug) and all the context you could provide (logs of exception if any would be great). Thanks!

**Comment by w0www** [comment]
thanks! finnally i select redmine_people of redmineCRM plugins. 

I am install a redmine with a lot of plugin that do redmine more better solution and i will have to develop or modify those plugins ;) when i have the solution in fine state i publicy to redmine forums and create a fork with solution complete

**Comment by nanego** [comment]
Just for information, about the behaviour of this plugin, when you add an organization to a project (through this path: project/settings/members), you also have to select some members and their roles. If you leave the organization empty, it will not be displayed after reloading the page.
We know it can be confusing. I should try to make it more explicit.
