### ISSUE TITLE
undefined method `to_prepare' for ActionDispatch::Callbacks:Class

### ISSUE THREAD

**Issue by violettomsk** [jbbarth/redmine_organizations#5]
ENV: Redmine 4.1.0
Ruby 2.4.4
Rails 5.2.1
Rake 13.0.1

`rake db:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/home/ywmobile/redmine/plugins/redmine_organizations/init.rb:4:in `<top (required)>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/home/ywmobile/redmine/lib/redmine/plugin.rb:181:in `block in load'
/home/ywmobile/redmine/lib/redmine/plugin.rb:172:in `each'
/home/ywmobile/redmine/lib/redmine/plugin.rb:172:in `load'
/home/ywmobile/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/home/ywmobile/redmine/config/environment.rb:16:in `<top (required)>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/ywmobile/.rvm/gems/ruby-2.4.4/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/ywmobile/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/home/ywmobile/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment`

**Comment by nanego** [comment]
It seems you are not using the latest version of the plugin.
